apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localhost-replacement
  namespace: app
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "localhost-replacement",
      "capabilities": { "ips": true },
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }'
