apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redirect-injector
  labels:
    app: redirect-injector
spec:
  selector:
    matchLabels:
      name: redirect-injector
  template:
    metadata:
      labels:
        name: redirect-injector
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: redirect-injector
          image: iptables-injector
          imagePullPolicy: Never
          command: ["/bin/sh"]
          args: ["./localhost-redirect.sh"]
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              drop:
                - ALL
            privileged: true
          volumeMounts:
          - name: containerd-socket
            mountPath: /var/run
            readOnly: false
      volumes:
      - name: containerd-socket
        hostPath:
          path: /var/run
