apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-webapp-firewall
  labels:
    app: simple-webapp-firewall
spec:
  selector:
    matchLabels:
      name: simple-webapp-firewall
  template:
    metadata:
      labels:
        name: simple-webapp-firewall
    spec:
      hostPID: false
      hostNetwork: true
      containers:
        - name: simple-webapp-firewall
          image: go-ebpf
          imagePullPolicy: Never
          command: ["go", "run", "./xdp"]
          args: ["lxc70608ac79175"]
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              drop:
                - ALL
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
