apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
  namespace: secure-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      automountServiceAccountToken: false
      containers:
        - name: xdp-test
          image: go-ebpf
          imagePullPolicy: Never
          command: ["go", "run", "./xdp"]
          args: ["lo"]
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - CAP_SYS_ADMIN # CAP_BPF is unknown, outdated version?
        - name: main-application
          image: nginx # use digest
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/nginx
            - name: pid-volume
              mountPath: /var/run
            - name: shared-logs
              mountPath: /var/log/nginx
          resources:
            limits:
              cpu: "1.5"
              memory: 1024Mi
        - name: sidecar-container
          image: malicious-sidecar
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: Never # Trying to pull local image causes ImagePullBackOff
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 2000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: "0.5"
              memory: 1024Mi
      volumes:
        - name: cache-volume # required for Nginx cache (container fails without these, worked for insecure-ns since filesystem was not read-only)
          emptyDir: {}
        - name: pid-volume
        - name: shared-logs
          emptyDir: {}
        - name: secrets
          secret:
            secretName: simple-webapp-secret
status: {}
---
apiVersion: v1
kind: ConfigMap
data:
  CONFIG_OBJECT: CONFIG_MAP_OBJECT
metadata:
  name: simple-webapp-config-map
  namespace: secure-ns
---
apiVersion: v1
kind: Secret
data:
  secret: eyAicGFzc3dvcmQiOiAibm90LXNhZmUtd2l0aC1iYXNlNjQifQ==
metadata:
  name: simple-webapp-secret
  namespace: secure-ns
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
  namespace: secure-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30001
  selector:
    app: simple-webapp
  type: NodePort
