apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: app
  annotations:
    k8s.v1.cni.cncf.io/policy-for: localhost-replacement
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: allow-statsd
  namespace: app
  annotations:
    k8s.v1.cni.cncf.io/policy-for: localhost-replacement
spec:
  podSelector:
    matchLabels:
      app: node-app-statsd
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: node-app
      ports:
        - protocol: UDP
          port: 8125
