apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-app-main
  namespace: multus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multus-app-main
  template:
    metadata:
      labels:
        app: multus-app-main
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{
            "name": "macvlan-static",
            "interface": "br0",
            "ips": [ "192.168.1.201/24" ]
          }]'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - minikube-m02
      automountServiceAccountToken: false
      containers:
        - name: main
          image: malicious-sidecar
          command: [
            "/bin/bash", "-c",
            'while true; do printf "HTTP/1.1 200 OK\n\n%s" "<html><head><title>Hello world</title></head><body><h1>Hello world</h1></body></html>" | netcat -l 8888; done'
          ]
          imagePullPolicy: Never # Trying to pull local image causes ImagePullBackOff
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              add:
                - NET_ADMIN
              drop:
                - ALL
          resources:
            limits:
              cpu: "1.5"
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: multus-app-main
  namespace: multus
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31001
  selector:
    app: multus-app-main
  type: NodePort
