apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-app-sidecar
  namespace: multus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multus-app-sidecar
  template:
    metadata:
      labels:
        app: multus-app-sidecar
      annotations:
        k8s.v1.cni.cncf.io/networks: default/macvlan-conf
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - minikube-m02
      automountServiceAccountToken: false
      containers:
        - name: sidecar
          image: malicious-sidecar
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: Never # Trying to pull local image causes ImagePullBackOff
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 2000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: "0.5"
              memory: 1024Mi
