apiVersion: v1
kind: Namespace
metadata:
  name: multus
  labels:
    name: multus
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-static
  namespace: multus
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-static",
      "capabilities": { "ips": true },
      "type": "bridge",
      "bridge": "mybr0",
      "isDefaultGateway": true,
      "ipMasq": true,
      "ipam": {
        "type": "static"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static
  namespace: multus
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "macvlan-static",
      "capabilities": { "ips": true },
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }'
