apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
        - name: main-application
          image: nginx
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log/nginx
        - name: sidecar-container
          image: busybox
          command: ["sh","-c","while true; do cat /var/log/nginx/access.log; sleep 30; done"]
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log/nginx
      volumes:
        - name: shared-logs
          emptyDir: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: simple-webapp
  type: NodePort