apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: insecure-ns
  name: simple-webapp-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-webapp-sa
  namespace: insecure-ns
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simple-webapp-rolebinding
  namespace: insecure-ns
subjects:
- kind: ServiceAccount
  name: simple-webapp-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: simple-webapp-role
  apiGroup: ""
