apiVersion: v1
kind: Namespace
metadata:
  name: multus
  labels:
    name: multus
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: multus
spec:
  # config: '{
  #   "cniVersion": "0.3.0",
  #   "type": "macvlan",
  #   "master": "eth0",
  #   "mode": "bridge",
  #   "ipam": {
  #     "type": "host-local",
  #     "subnet": "192.168.1.0/24",
  #     "rangeStart": "192.168.1.201",
  #     "rangeEnd": "192.168.1.254",
  #     "routes": [
  #       {
  #         "dst": "192.168.1.0/24",
  #         "gateway": "192.168.1.1"
  #       }
  #     ],
  #     "gateway": "192.168.1.1"
  #     }
  #   }'
  # config: '{
  #     "cniVersion": "0.3.0",
  #     "type": "macvlan",
  #     "master": "eth0",
  #     "mode": "bridge",
  #     "ipam": {
  #       "type": "host-local",
  #       "subnet": "192.168.1.0/24",
  #       "rangeStart": "192.168.1.201",
  #       "rangeEnd": "192.168.1.254",
  #       "routes": [
  #         { "dst": "0.0.0.0/0" }
  #       ],
  #       "gateway": "192.168.1.1"
  #     }
  #   }'
  config: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "mybr0",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.201",
        "rangeEnd": "192.168.1.254"
      }
    }'
